name: Docker Image CI

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - ".github/**"
      - "*.md"
      - "LICENSE"
  pull_request:
    branches: [ main ]
    paths-ignore:
      - ".github/**"
      - "*.md"
      - "LICENSE"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag certbot_only:$(date +%s)
